# Generated by Django 3.1.7 on 2021-03-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to='static/assets/img'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='bullet',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='summary',
            name='bullet',
            field=models.TextField(),
        ),
    ]
