# Generated by Django 3.1.7 on 2021-03-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210318_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='static/assets/img'),
        ),
    ]
