# Generated by Django 3.1.7 on 2021-03-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_about_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bullets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bullet', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='summary',
            name='bullet',
        ),
    ]
