# Generated by Django 3.1.7 on 2021-03-18 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20210318_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='bullet',
        ),
        migrations.AddField(
            model_name='bullet',
            name='experience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bullet', to='portfolio.experience'),
        ),
    ]
